name: Release Test

on:
  push:
    tags:
      - 'v*'
      - 'test-*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo tag
        run: |
          echo "Triggered by tag: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"
